# Generated by Django 6.0.6 on 2026-06-19 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='actionlog',
            new_name='common_acti_action_ec63ae_idx',
            old_name='common_act_action_idx',
        ),
        migrations.RenameIndex(
            model_name='actionlog',
            new_name='common_acti_user_id_928c18_idx',
            old_name='common_act_user_id_idx',
        ),
    ]
